comedianVotes = [];
//this was an empty array

comedianStats = function(filepath, comedian) {
  this.filepath = filepath;
  this.comedian = comedian;
  this.votes = 0;
  comedianVotes.push(this); //pushing this object in to comedianVotes array
};
//this is a constructor function that creates information about comedians
//auto pushed to an empty array

//below is where the image file is located and the name of the corresponding comedian
//i am instatiating new comedianStat objects

new comedianStats('../images/amy.jpg', 'Amy Poehler');
new comedianStats('../images/aziz.jpg', 'Aziz Ansari');
new comedianStats('../images/billburr.jpg', 'Bill Burr');
new comedianStats('../images/carlin.jpg', 'George Carlin');
new comedianStats('../images/chappelle.jpg', 'Dave Chappelle');
new comedianStats('../images/chelsea.jpg', 'Chelsea Peretti');
new comedianStats('../images/doug.jpg', 'Doug Benson');
new comedianStats('../images/esther.jpg', 'Lil\' Esther');
new comedianStats('../images/louis.jpg', 'Louis CK');
new comedianStats('../images/richard.jpg', 'Richard Pryor');
new comedianStats('../images/sarah.jpg', 'Sarah Silverman');
new comedianStats('../images/seinfield.jpg', 'Jerry Seinfield');

//var created to fill the DOM element w id image1/image2
var imageFirst = document.getElementById('image1');
var imageSecond = document.getElementById('image2');
//same thing is happening with the image's corresponing name
var nameFirst = document.getElementById('named1');   //name info
var nameSecond = document.getElementById('named2');  //name info






//the tracker object
var tracker = {
  genRandChoice: function() { //measures length of comedianVotes array- chooses
  //randomly one of the index positions to grab a comedian object
    return Math.floor(Math.random() * comedianVotes.length);
  },
  getImages: function() { //uses number generated by genRandChoice function and acts as a index
  // position of the comedianVotes array
    var img1 = comedianVotes[this.genRandChoice()];
    var img2 = comedianVotes[this.genRandChoice()];

    while (img1 === img2) { //while loop that makes img2 run through the comedianVotes list again and
      img2 = comedianVotes[this.genRandChoice()]; //pick a new comedianStats object
    }

    //still inside tracker function, i use dot notation? like innerHTML. i make
    //img1/img2 which are declared 8 lines up equal to imageFirst.src/imageSecond.src

    imageFirst.src = img1.filepath; //img1/2 accesses the comedianVotes . filepath
    imageSecond.src = img2.filepath;
    imageFirst.data = comedianVotes.indexOf(img1); //making .data attribute of imageFirst = to a position in the comedianVotes array
    imageSecond.data = comedianVotes.indexOf(img2); //same as above

    imageFirst.name = img1.comedian; //img1/2 access comedianVotes . comedian
    console.log(imageFirst.name);
    document.getElementById("named1").innerHTML = imageFirst.name;
    imageSecond.name = img2.comedian;
    console.log(imageSecond.name);
    document.getElementById("named2").innerHTML = imageSecond.name;
  },

  voteForOne: function() {
    var ourNumber = imageFirst.data; //this is related to line 61, creating a var to represent position in the comedianVotes array
    comedianVotes[ourNumber].votes += 1; //adds vote to .data attribute of an image that was added to the array
    barData.datasets[0].data[ourNumber] += 1; //finds location on bar chart at index 0, adds +1 to .data value
    new Chart(income).Bar(barData); //makes new chart
    tracker.getImages(); //calls up two new pics
    document.getElementById("playAgain").innerHTML = "Vote again!"; //when clicked, message displays
  },

  voteForTwo: function() {
    var ourNumber = imageSecond.data;//this is related to line 62----same as above
    comedianVotes[ourNumber].votes += 1;
    barData.datasets[0].data[ourNumber] += 1;
    new Chart(income).Bar(barData);
    tracker.getImages();
    document.getElementById("playAgain").innerHTML = "Vote again!";
  },

};

var barData = {
  labels: [],
  datasets: [
    {
      fillColor: '#000000',
      strokeColor: '#000000',
      data: []
    }
  ]
}

for (var i = 0; i < comedianVotes.length; i++) {
  barData.labels.push(comedianVotes[i].comedian);
  barData.datasets[0].data.push(0);
}

var income = document.getElementById("income").getContext("2d");
new Chart(income).Bar(barData);








imageFirst.addEventListener("click", tracker.voteForOne);
imageSecond.addEventListener("click", tracker.voteForTwo);


tracker.getImages();

